### PR TITLE
Add test coverage report

### LINKED ISSUE #456: Add coverage to test running
In order to find gaps in testing the testing process should run coverage.

### PR DESCRIPTION
**Pull request by Amertz08**
#### Title

Please **pick a concise, informative and complete title** for your PR.
The title is important because it will appear in [our change log](https://github.com/RaRe-Technologies/smart_open/blob/master/CHANGELOG.md).

#### Motivation

This PR adds test coverage config to find gaps in testing.

If you're fixing a bug, link to the issue number like so:

- Fixes #456 

If you're adding a new feature, then consider opening a ticket and discussing it with the maintainers before you actually do the hard work.

#### Tests

If you're fixing a bug, consider [test-driven development](https://en.wikipedia.org/wiki/Test-driven_development):

1. Create a unit test that demonstrates the bug. The test should **fail**.
2. Implement your bug fix.
3. The test you created should now **pass**.

If you're implementing a new feature, include unit tests for it.

Make sure all existing unit tests pass.
You can run them locally using:

    pytest smart_open

If there are any failures, please fix them before creating the PR (or mark it as WIP, see below).

#### Work in progress

If you're still working on your PR, include "WIP" in the title.
We'll skip reviewing it for the time being.
Once you're ready to review, remove the "WIP" from the title, and ping one of the maintainers (e.g. mpenkov).

#### Checklist

Before you create the PR, please make sure you have:

- [ ] Picked a concise, informative and complete title
- [ ] Clearly explained the motivation behind the PR
- [ ] Linked to any existing issues that your PR will be solving
- [ ] Included tests for any new functionality
- [ ] Checked that all unit tests pass

#### Workflow

Please avoid rebasing and force-pushing to the branch of the PR once a review is in progress.
Rebasing can make your commits look a bit cleaner, but it also makes life more difficult from the reviewer, because they are no longer able to distinguish between code that has already been reviewed, and unreviewed code.

### CODE REVIEW

**Comment by Amertz08** [comment]
Looks like lots of spammy warning messages.
```
Coverage.py warning: ...
```
I'll try and figure out how to filter those. Also might consider altering how tox pip installs stuff to use the `-q` flag so it will install quiet.

**Comment by Amertz08** [comment]
Setup is there and appears to be working. Not sure what is up with the warnings. The coverage.py code appears to print them via the `print` function and not via actual warnings so using the standard warning filtering does not appear to work. Will look into why those errors are appearing. For some reason valid coverage files are not being generated or so it appears.

**Comment by mpenkov** [comment]
I wonder if using something like https://coveralls.io/ is better than doing it ourselves. They track history, etc. and are free for open source projects. WDYT?

**Comment by Amertz08** [comment]
Yeah I've always wanted to use it. Kinda forgot. I'll poke around with it today.

**Comment by mpenkov** [comment]
@Amertz08 I ended up doing this myself: https://github.com/RaRe-Technologies/smart_open/pull/462. It's now merged into master. Please have a look and let me know if there's anything else we can add.

**Pull request closed without merging**
