### PR TITLE
Fix bug where opening files in GCS forgets to define a name field

### LINKED ISSUE #505: Opening GCS files via `smart_open.open` fails to add the `name` field to the file object
#### Problem description

Currently the `gcs.open` function returns a Reader or Writer object, but does not add a `name` field to the object. This creates a problem when trying to open compressed files in GCS, since smart open's compression wrapper relies on the `name` field to choose the decompression algorithm. Thankfully, the problem is relatively straightforward to fix by slightly updating the `open` function in `gcs.py`:

Here is the current version of `gcs.open`:
```
if mode == constants.READ_BINARY:
        return Reader(
            bucket_id,
            blob_id,
            buffer_size=buffer_size,
            line_terminator=constants.BINARY_NEWLINE,
            client=client,
        )
    elif mode == constants.WRITE_BINARY:
        return Writer(
            bucket_id,
            blob_id,
            min_part_size=min_part_size,
            client=client,
        )
    else:
        raise NotImplementedError('GCS support for mode %r not implemented' % mode)
```

Here is the updated version that would fix the issue:
```
if mode == constants.READ_BINARY:
        fileobj = Reader(
            bucket_id,
            blob_id,
            buffer_size=buffer_size,
            line_terminator=constants.BINARY_NEWLINE,
            client=client,
        )
    elif mode == constants.WRITE_BINARY:
        fileobj = Writer(
            bucket_id,
            blob_id,
            min_part_size=min_part_size,
            client=client,
        )
    else:
        raise NotImplementedError('GCS support for mode %r not implemented' % mode)

    fileobj.name = blob_id
    return fileobj
```

I tried to push a branch & open a pull request that makes the fix, but it looks like I don't have access rights, so I made this issue instead.

### PR DESCRIPTION
**Pull request by todor-markov**
#### Motivation

Fixes #505 

#### Checklist

Before you create the PR, please make sure you have:

- [X] Picked a concise, informative and complete title
- [X] Clearly explained the motivation behind the PR
- [X] Linked to any existing issues that your PR will be solving
- [ ] Included tests for any new functionality
- [X] Checked that all unit tests pass

### CODE REVIEW

**Comment by mpenkov** [comment]
@todor-markov Thank you for making the PR! Can you add a unit test that checks for your new funcitonality?

**Comment by bsikander** [comment]
+1 for the PR. I have been messing with this for 2 hours now and this is the exact issue. Could we please speed up the process to get this in.

**Comment by bsikander** [comment]
Was it working in any version?

**Comment by mpenkov** [comment]
> Was it working in any version?

Yes, because of [this](https://github.com/RaRe-Technologies/smart_open/blob/0a3619144a75ea002304c487b8f8a9ee2c867c33/smart_open/smart_open_lib.py#L402).

**Comment by bsikander** [comment]
I am new to smart-open, so, I don't understand why it was working before.

Btw, i don't understand the reason for these TODOs in the code. In added logging to my code to find the problem and got TODO multiple times. Was not helpful.
https://github.com/RaRe-Technologies/smart_open/blob/0a3619144a75ea002304c487b8f8a9ee2c867c33/smart_open/smart_open_lib.py#L403

**Comment by bsikander** [comment]
Thank you for adding the tests.

**Comment by mpenkov** [comment]
> I am new to smart-open, so, I don't understand why it was working before.

This PR adds .name attribute to file objects created by the GCS backend. Previously, this attribute was missing. However, the code that relied on the .name attribute was robust enough to handle its absense.

> Btw, i don't understand the reason for these TODOs in the code. In added logging to my code to find the problem and got TODO multiple times.

TODOs are serve as a reminder to developers about parts of the code that are incomplete (or require attention for whatever reason). They are not ideal - in retrospect, it would have been better to fix the underlying problem, or create a github ticket to track the issue. Hindsight is always 20/20.

> Was not helpful.

You're welcome to make PRs to make things more helpful.

**Comment by mpenkov** [comment]
Thank you @todor-markov ! Congratulations on your first contribution to smart_open :1st_place_medal:

**Pull request merged**
