### PR TITLE
[WIP] Updated ver of httpretty and requests

### PR DESCRIPTION
**Pull request by tmylk**
Expect fix to #40 and and #51 in the new httpretty version

### CODE REVIEW

**Comment by tmylk** [comment]
Py3 fails with 
httpretty == 0.8.14
requests== 2.9.1

```code
Traceback (most recent call last):
  File "/opt/python/3.3.5/lib/python3.3/threading.py", line 901, in _bootstrap_inner
    self.run()
  File "/opt/python/3.3.5/lib/python3.3/threading.py", line 858, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python/3.3.5/lib/python3.3/multiprocessing/pool.py", line 347, in _handle_tasks
    for i, task in enumerate(taskseq):
  File "/opt/python/3.3.5/lib/python3.3/multiprocessing/pool.py", line 274, in <genexpr>
    self._taskqueue.put((((result._job, i, func, (x,), {})
  File "/home/travis/build/piskvorky/smart_open/smart_open/smart_open_lib.py", line 636, in <genexpr>
    keys = (key for key in bucket.list(prefix=prefix) if accept_key(key.name))
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/boto/s3/bucketlistresultset.py", line 34, in bucket_lister
    encoding_type=encoding_type)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/boto/s3/bucket.py", line 473, in get_all_keys
    '', headers, **params)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/boto/s3/bucket.py", line 399, in _get_all
    query_args=query_args)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/boto/s3/connection.py", line 665, in make_request
    retry_handler=retry_handler
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/boto/connection.py", line 944, in _mexe
    response = connection.getresponse()
  File "/opt/python/3.3.5/lib/python3.3/http/client.py", line 1147, in getresponse
    response.begin()
  File "/opt/python/3.3.5/lib/python3.3/http/client.py", line 382, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "/opt/python/3.3.5/lib/python3.3/http/client.py", line 264, in parse_headers
    raise LineTooLong("header line")
http.client.LineTooLong: got more than 65536 bytes when reading header line
```

**Comment by tmylk** [comment]
Requests version updated in https://github.com/piskvorky/smart_open/pull/67

Httpretty version is still fixed. @nikicc Is there any need to bump it up?

**Comment by nikicc** [comment]
@tmylk: the bump of httpretty to `0.8.12` or `0.8.14` should fix the issue #40, which is causing problems for us. Though, since test are failing with these versions, we probably need to wait for `0.8.15` and hope for the best :smile:

**Comment by tmylk** [comment]
No longer pinned so this PR is not needed.

**Pull request closed without merging**
