### PR TITLE
Correctly pass boto3 resource to writers

### LINKED ISSUE #575: Boto3 resource ignored for s3 uploads
#### Problem description
When specifying custom aws boto3 resource such as custom endpoint_url, the resource variable is ignored for uploads.
The expected result is to use the specified resource. The actual result is that the specified resource is ignored.

#### Steps/code to reproduce the problem

```python
transport_params = {'session': s3_session, 'resource': s3_session.resource('s3', endpoint_url="http://<private_url>:9000"}
with open("s3://testing/abc.log", mode='wb', transport_params=transport_params) as out_file:
   file.write(b'abc\n')

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/smart_open/s3.py", line 721, in __init__
    self._mp = _retry_if_failed(partial)
  File "/usr/local/lib/python3.6/dist-packages/smart_open/s3.py", line 1003, in _retry_if_failed
    return partial()
  File "/usr/local/lib/python3.6/dist-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the CreateMultipartUpload operation: The AWS Access Key Id you provided does not exist in our records.

```

#### Versions

Please provide the output of:

```python
Linux-5.4.0-1029-aws-aarch64-with-Ubuntu-18.04-bionic
3.6.9 (default, Oct  8 2020, 12:12:24)
smart_open 4.1.0
```

### PR DESCRIPTION
**Pull request by jackluo923**
#### Title

Fixed bug where boto3 resource are ignored for object upload

#### Motivation

- Fixes #575

### CODE REVIEW

**Comment by mpenkov** [comment]
Thanks for picking this up! Can you please add some tests?

**Comment by jackluo923** [comment]
@mpenkov Would extending test_minio.py under the test directory to handle write request in addition to read request be okay or a separate test file is needed?

**Comment by mpenkov** [comment]
I think the best way to test this would be a few new test cases in test_s3.py. You could [wrap the resource in a Mock object](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock) and then check that the resource was correctly re-used by smart_open. Does that make sense?

**Comment by mpenkov** [comment]
I added the tests myself. Thank you for your contribution @jackluo923 !

**Pull request merged**
