### PR TITLE
Add max_concurrency support for azure

### PR DESCRIPTION
**Pull request by omBratteng**
#### Motivation

`download_blob` in `azure.storage.blob` supports setting a max concurrency for downloading blobs, which can improve download speeds. In a similar implementation of `smart_open`, we've noticed that downloading a 313 GiB file averaged 83 minutes download time, whilst `smart_open` at 122 minutes.

Some benchmarks (*note*: these also calculates the sha256 checksum of the blob downloaded)
`buffer_size` is set to `268435456`

<table>
<tr>
	<th>smart_open (max_concurrency=4)
	<th>smart_open (max_concurrency=1)
	<th>our implementation (max_concurrency=4)
	<th>our implementation (max_concurrency=1)
<tr>
	<td>49.8843s
	<td>69.1530s
	<td>49.7495s
	<td>69.4825s
<tr>
	<td>49.3389s
	<td>69.1241s
	<td>49.0315s
	<td>68.9774s
<tr>
	<td>49.3781s
	<td>66.0186s
	<td>48.4432s
	<td>69.1307s
<tr>
	<th>avg: 49.5338s
	<th>avg: 68.0986s
	<th>avg: 49.0747s
	<th>avg: 69.1969s
</table>

As one can see, setting max_concurrency to 4, gives a decrease of 27%, which I think is significant, and is a nice feature to add to the `azure` connector in `smart_open`

#### Tests

> If there are any failures, please fix them before creating the PR (or mark it as WIP, see below).

Failing tests seems to not be related to `azure`, but `s3`

#### Checklist

Before you create the PR, please make sure you have:

- [x] Picked a concise, informative and complete title
- [X] Clearly explained the motivation behind the PR
- [ ] Linked to any existing issues that your PR will be solving
- [x] Included tests for any new functionality
- [ ] Checked that all unit tests pass

### CODE REVIEW

**Comment by mpenkov** [comment]
@omBratteng Could you please enable maintainer edits for this PR? I need to push some changes to get the tests working, but I'm getting permission denied.

**Comment by omBratteng** [comment]
@mpenkov I can't see where to enable it after I've created the PR, but I've added you to our fork, so you should be able to edit it there directly.
If not, I can close and open a new PR.

**Comment by mpenkov** [comment]
I'd rather get things working in this PR. I'm still getting permission denied, though.

Can you please have a look here: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

That has instructions for giving maintainer access to PRs.

**Comment by omBratteng** [comment]
Sorry @mpenkov, I can't seem to have that option anywhere. If it's just to get the latest commits in from the develop branch, I can do a rebase.

**Comment by mpenkov** [comment]
No need to rebase, just merge the develop HEAD.

**Comment by omBratteng** [comment]
Done

**Review by mpenkov — APPROVED** [review]
Looks good to me!

**Comment by mpenkov** [comment]
Thank you for your contribution @omBratteng !

**Pull request merged**
