### PR TITLE
Add support for .xz / lzma

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Re-opened https://github.com/RaRe-Technologies/smart_open/pull/260

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@mpenkov All review addressed except https://github.com/RaRe-Technologies/smart_open/pull/260#discussion_r258734796 because I feel that refactoring the test suite is a separate task. WDYT?

**Comment by vmarkovtsev** [comment]
@mpenkov @piskvorky ping

**Comment by tdhopper** [comment]
This is breaking my builds due to needing `liblzma-dev`. Would there be any interest in a PR making this an optional dependency?

**Comment by tdhopper** [comment]
See #281

**Pull request merged**
