### PR TITLE
[WIP] Add tox

### LINKED ISSUE #216: Improve tooling for repository
We need to improve the tooling of the repository to increase code-quality and simplify test process
- [x] Add style-checker (pycodestyle, flake8, any)
- [x] Add tox that should allow
  - [x] Run tests with all python version
  - [x] Run style-checkers
  - [x] (optional) Run integration tests

**Discussion:** @piskvorky @mpenkov wdyt to add automatic code-formatter like  https://github.com/google/yapf or https://github.com/ambv/black, I want to drop all discussions about code-style at all (honestly, I want to do it for Gensim, but `smart_open` are good candidate for test this approach, because it simple and small).

Why I think this is useful:
- auto code-formatting (no need to remember about style always)
- no comments about code-formatting
- always clean code

### PR DESCRIPTION
**Pull request by menshikh-iv**
Fix #216 

Add tox to the current project

Missing
- Execute the benchmark on CI (tox issues, commented for now)

### CODE REVIEW

**Comment by mpenkov** [comment]
@menshikh-iv Ping ;)

**Comment by menshikh-iv** [comment]
@mpenkov I'll back soon (I hope), sorry for waiting.

**Comment by mpenkov** [comment]
@menshikh-iv Ping ;)

**Comment by menshikh-iv** [comment]
Continued in https://github.com/RaRe-Technologies/smart_open/pull/439

**Pull request closed without merging**
