### PR TITLE
Make UploadFailedError picklable

### PR DESCRIPTION
**Pull request by birgerbr**
#### Motivation

The [ray](https://github.com/ray-project/ray) library is not able to handle unpicklable exceptions sufficiently, see https://github.com/ray-project/ray/issues/21075 for a similar issue.

#### Tests

The [PickleUploadFailedTest](https://github.com/Imerso3D/smart_open/blob/e4016299a728ea6f346e3780b1da5900450a971f/smart_open/tests/test_gcs.py#L932) test case has been added to `test_gcs.py`.

#### Checklist

Before you create the PR, please make sure you have:

- [x] Picked a concise, informative and complete title
- [x] Clearly explained the motivation behind the PR
- [x] Linked to any existing issues that your PR will be solving
- [x] Included tests for any new functionality
- [x] Checked that all unit tests pass

### CODE REVIEW

**Comment by mpenkov** [comment]
Hi, can you please make this PR editable for maintainers?

**Comment by birgerbr** [comment]
> Hi, can you please make this PR editable for maintainers?
> 
> As a maintainer, I'd like to merge the most recent upstream into your PR, but need you to give me permission first.

I added you with write permission to https://github.com/Imerso3D/smart_open.
Is that sufficient?

**Comment by mpenkov** [comment]
Yes, that's a little excessive (you can set it for individual PRs instead of the whole repo) but it will get the job done. Thanks.

**Review by mpenkov — APPROVED** [review]

**Comment by birgerbr** [comment]
> Yes, that's a little excessive (you can set it for individual PRs instead of the whole repo) but it will get the job done. Thanks.

Thanks for the info. I did not know that. :+1:

**Pull request merged**
