### PR TITLE
Added support for viewfs:// URLs.

### LINKED ISSUE #645: Request Support for `viewfs://`
#### Problem description

Hi, smart_open currently supports `hdfs://`, `viewfs://` is also a hadoop file system which is similar to `hdfs://`.

I find that `tf.io.gfile.GFile` of tensorflow can support both `hdfs://` and `viewfs://`, is it possible that smart_open add support for `viewfs://`?

Thanks~

### PR DESCRIPTION
**Pull request by ChandanChainani**
As stated by @zhezh that hdfs support viewfs
we just need to convert viewfs to hdfs uri internally
and it will work.

Fixes #645

### CODE REVIEW

**Comment by ChandanChainani** [comment]
@mpenkov could you take a look?

**Comment by mpenkov** [comment]
@ChandanChainani Are you able to finish this PR?

**Comment by ChandanChainani** [comment]
@mpenkov I didn't got the chance to complete the test changes.

Please guide me how can i write test cases for viewfs, since we are using hdfs internally same test cases should work.

**Comment by ChandanChainani** [comment]
@mpenkov any suggestion on above comment.

**Comment by mpenkov** [comment]
I added some tests. Thank you for your work!

**Pull request merged**
