### PR TITLE
[WIP] Use azurite in CI

### LINKED ISSUE #502: Run Azure integration tests in CI
We can use [Azurite](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite) to run unmocked unit tests and integration tests in CI without needing an Azure account. This will allow us to run our entire test suite for Azure in CI with no additional costs.

### PR DESCRIPTION
**Pull request by petedannemann**
#### Motivation

```
- Fixes #502 
```

#### Checklist

Before you create the PR, please make sure you have:

- [x] Picked a concise, informative and complete title
- [x] Clearly explained the motivation behind the PR
- [x] Linked to any existing issues that your PR will be solving
- [ ] Included tests for any new functionality
- [ ] Checked that all unit tests pass

### CODE REVIEW

**Comment by petedannemann** [comment]
Azurite sucks and is very incomplete

**Comment by mpenkov** [comment]
Is there any positive feedback we can leave for https://github.com/azure/azurite, or are things really that bad?

**Comment by petedannemann** [comment]
I think I was too harsh but I believe since Azure released new breaking API changes this year Azurite is trying to play catch up and many features are missing in the new APIs. I think this is directly related to what we saw with the old Azure pypi package having breaking API changes. I would have to do more digging to figure out exactly what features are missing but if you look at the Travis logs for the unmocked job you will see a ton of Azurite not implemented errors

**Comment by petedannemann** [comment]
The project itself looks good and of high quality (not a node.js fan but I am trying to stay objective). I think things are just still in development for the new API version and that is totally understandable

**Comment by mpenkov** [comment]
Is there anything we can point out for them to fix, by opening a new ticket? Or is it already a known problem?

**Pull request closed without merging**
