### PR TITLE
Revert "Add Appveyor build"

### PR DESCRIPTION
**Pull request by mpenkov**
Reverts RaRe-Technologies/smart_open#479

This should have been merged into develop, not master.

### CODE REVIEW

**Comment by piskvorky** [comment]
This is gonna be a common thing. How will contributors know to open PRs against `develop`, not `master`?

**Comment by mpenkov** [comment]
All of them, because I switched the default branch to develop, and rebased outstanding PRs to that branch.

This is something I should have done when creating the develop branch.

**Comment by piskvorky** [comment]
But doesn't that beat the purpose? Now Github shows the README from `develop` too. What did we gain?

**Comment by mpenkov** [comment]
The gain is a clearer distinction between stable released code (master) and unstable code still in development (develop). Each commit on master will correspond to a single release. Each commit on develop will correspond to a feature or bugfix (merged PR). 

It's also consistent with how we handle branches with gensim. This reduces the maintainer's cognitive load when making releases.

**Comment by piskvorky** [comment]
> Each commit on master will correspond to a single release. 

Do you mean squashing each release into a single commit? That doesn't sound like a good idea. We don't do that for Gensim either.

Squashing PRs into a single commit makes more sense, although I'm not a fan of rewriting history even there.

**Comment by mpenkov** [comment]
Sorry, I meant "each _merge_ to master" instead of "each _commit_ to master".

With gensim, the work happens on develop. When we do a new release, we:

1. Create a "release-$version" branch off the develop HEAD
2. Make any release specific changes on that branch (including version bumps, updating the changelog, etc)
3. Merge the release branch into master (this is the merge I was referring to)
4. Release
5. Merge master into develop (to include the changes in 2)

This way, when people look at master, they see what was last released. When they look at develop, they see what we're currently working on.

Does that make more sense?

**Comment by piskvorky** [comment]
Sure, thanks. That's the workflow I created :)

**Comment by mpenkov** [comment]
Cool. Basically, I'm trying to get gensim and smart_open to use the same workflow (to the extent its possible) to simplify maintenance.

**Pull request merged**
