### PR TITLE
Reconnect inactive sftp clients automatically

### PR DESCRIPTION
**Pull request by Kache**
Fix: #714

Also fix dependency installation for ssh backend

### CODE REVIEW

**Comment by Kache** [comment]
fyi @mpenkov

**Comment by Kache** [comment]
@mpenkov sorry about that, ready now

**Comment by mpenkov** [comment]
@Kache Please enable commits by maintainers. I'd like to push some changes to your branch as part of this PR.

**Comment by Kache** [comment]
@mpenkov done

**Comment by mpenkov** [comment]
Merged. Thank you @Kache !

**Pull request merged**
