### PR TITLE
SSH/SCP/SFTP protocol support

### PR DESCRIPTION
**Pull request by val314159**
Uses paramiko library (nice and low level)

Solves: Issue https://github.com/piskvorky/smart_open/issues/36

### CODE REVIEW

**Comment by piskvorky** [comment]
Thanks a lot @val314159 !

@tmylk please review & prepare for merge.

**Comment by ziky90** [comment]
It looks much better than #44 
Though I'm missing some tests in this PR.

**Comment by tmylk** [comment]
Tests from #44 need to be added here, then will be ready to merge. Should be a quick win.

Fixes #36 and #33

**Comment by val314159** [comment]
I'm not really sure how to test this exactly.... how do i fake out an entire ssh server?

**Comment by tmylk** [comment]
Hi @val314159 , thank you for coming back to this!
For mocking one can use `mock.patch` as in [issue 44](https://github.com/RaRe-Technologies/smart_open/pull/44/files#diff-36c1f33ff2d12844dc387270ca11d040R125)

**Comment by menshikh-iv** [comment]
Ping @val314159, what's a status of this PR?

**Comment by menshikh-iv** [comment]
ping @val314159, what's a status of this PR?

**Comment by menshikh-iv** [comment]
I close because this PR is abandoned.

**Comment by piskvorky** [comment]
@menshikh-iv looks like only some tests are missing here -- can you add that and merge?

**Comment by menshikh-iv** [comment]
Need to finish this PR

**Comment by menshikh-iv** [comment]
What's missing:
- add `paramiko` dependency (are we fine with it @piskvorky, this is LGPL dependency)
- parametrize port (`ssh` not always on 22)
- add possibility to specify a key
- resolve merge conflict (this are really large)
- add tests (unit + integration)
  - check how it works with user/pass, ssh key auth, etc
  - how it works without username at all (only host, is this can retrieve a key from disk?)
 

anything else missing @mpenkov ?

**Comment by piskvorky** [comment]
Yes, linking against LGPL (without modifications) is fine.

**Comment by luckydonald** [comment]
This would come in handy.

**Comment by mpenkov** [comment]
Continued in https://github.com/RaRe-Technologies/smart_open/pull/267

**Pull request closed without merging**
